library(readxl)
BostonHousePriceIndex <- read_excel("~/EC 245/BostonHousePriceIndex.xlsx",
sheet = "Monthly")
View(BostonHousePriceIndex)
BHPI <- ts(BostonHousePriceIndex$Boston, start(1987,1), frequency = 12)
plot(BHPI)
hist(BHPI)
logBHPI <- log(BHPI)
plot(logBHPI)
diffBHPI <- diff(logBHPI)
diff(logBHPI)
summary(diffBHPI)
sd(diffBHPI)
average_growth_rate <- ((1+diffBHPI)^12)-1
summary(average_growth_rate)
hist(average_growth_rate)
hist(average_growth_rate, freq = FALSE)
t.test(average_growth_rate, mu = 0)
recent_average_growth_rate <- average_growth_rate[300:380]
t.test(recent_average_growth_rate, mu = 0)
library(car)
library(dynlm)
library(lmtest)
model <- dynlm(BHPI~trend(BHPI))
summary(model)
logmodel <- dynlm(logBHPI~trend(logBHPI))
summary(logmodel)
ts.plot(logBHPI, logmodel$fitted.values, col = c("black", "red"))
dwtest(logmodel)
GrowthFit <- exp(logmodel$fitted.values)
ts.plot(BHPI, GrowthFit, col = c("black", "red"))
mean(BHPI)
library(forecast)
ma50 <- ma(logBHPI, 50)
ts.plot(logBHPI, ma50, col = c("black", "red"))
sem <- HoltWinters(x = logBHPI, alpha = 0.15, beta=FALSE, gamma = FALSE)
sem
plot(sem)
difflogBHPI <- diff(logBHPI)
Acf(difflogBHPI, 500)
Pacf(difflogBHPI)
Box.test(difflogBHPI, 12, "Lj")
Arima1 <- Arima(difflogBHPI, c(7,0,0))
Arima2 <- Arima(difflogBHPI, c(7,0,1))
summary(Arima2)
Arima3 <- Arima(difflogBHPI, c(7,0,2))
summary(Arima3)
AIC(Arima1, Arima2, Arima3)
BIC(Arima1, Arima2, Arima3)
plot(Arima1)
plot(Arima2)
plot(Arima3)
Arima1Training <- Arima(difflogBHPI[344:380], c(7,0,0))
Arima1Testing <- Arima(difflogBHPI[344:380], c(7,0,0))
Arima2Training <- Arima(difflogBHPI[1:343], c(7,0,1))
Arima2Testing <- Arima(difflogBHPI[344:380], c(7,0,1))
t.test(Arima1$residuals)
t.test(Arima2$residuals)
Box.test(Arima1$residuals, 12, "Lj")
Box.test(Arima2$residuals, 12, "Lj")
summary(Arima1Testing)
summary(Arima2Testing)
EfficiencyTest1 <- lm(Arima1$residuals~Arima1$fitted)
EfficiencyTest2 <- lm(Arima2$residuals~Arima2$fitted)
summary(EfficiencyTest1)
summary(EfficiencyTest2)
Forecast1 <- forecast(Arima1, 36, 95)
plot(Forecast1)
print(Forecast1)
Forecast2 <- forecast(Arima2, 36, 95)
plot(Forecast2)
print(Forecast2)
ts.plot(Forecast1$mean, Forecast1$lower, Forecast1$upper, col = c("black", "blue", "red"))
ts.plot(Forecast2$mean, Forecast2$lower, Forecast2$upper, col = c("black", "blue", "red"))
Forecast1Table <- data.frame(Forecast1$lower, Forecast1$mean, Forecast1$upper)
Forecast2Table <- data.frame(Forecast2$lower, Forecast2$mean, Forecast2$upper)
Forecast2Table
library(lmtest)
Forecast1 <- forecast(Arima1, 36)
Forecast1
Forecast2 <- forecast(Arima2, 36)
Forecast2
plot(Forecast1$mean)
plot(Forecast2$mean)
plot(Forecast1$lower)
plot(Forecast2$lower)
plot(Forecast1$upper)
plot(Forecast2$upper)
hw1 <- Forecast1$mean - Forecast1$lower
hw2 <- Forecast2$mean - Forecast2$lower
hw3 <- Forecast1$mean - Forecast1$upper
hw4 <- Forecast2$mean - Forecast2$upper
hw1
hw2
hw3
hw4
Model3 <- Arima(logBHPI, c(7,0,0))
forecast(Model3, 36)
summary(Model3)
Box.test(Model3$residuals, 12, "Lj", 8)
coeftest(Model3)
Model3 <- Arima(logBHPI, c(5,0,0))
Box.test(Model3$residuals, 12, "Lj", 6)
coeftest(Model3)
plot(Model3)
Model4 <- auto.arima(logBHPI, ic="aic")
summary(Model4)
Model5 <- auto.arima(logBHPI, stepwise = FALSE, seasonal = FALSE)
summary(Model5)
Box.test(Model4$residuals, 12, "Lj", 5)
Box.test(Model5$residuals, 12, "Lj", 5)
coeftest(Model4)
coeftest(Model5)
plot(Model4)
plot(Model5)
Model1Training <- Arima(logBHPI[1:343], c(7,0,0))
Model1Forecast <- Arima(logBHPI[344:381], model = Arima1)
summary(Model1Training)
summary(Model1Forecast)
t.test(Model1Forecast$residuals)
Box.test(Model1Forecast$residuals, 12, "Lj")
EfficiencyModel1 <- lm(Model1Forecast$residuals~Model1Forecast$fitted)
summary(EfficiencyModel1)
lht(EfficiencyModel1, "(Intercept)=Model1Forecast$fitted")
Model2Training <- Arima(logBHPI[1:343], c(7,0,1))
Model2Forecast <- Arima(logBHPI[344:381], model = Arima2)
summary(Model2Training)
summary(Model2Forecast)
t.test(Model2Forecast$residuals)
Box.test(Model2Forecast$residuals, 12, "Lj")
EfficiencyModel2 <- lm(Model2Forecast$residuals~Model2Forecast$fitted)
summary(EfficiencyModel2)
lht(EfficiencyModel2, "(Intercept)=Model2Forecast$fitted")
e1 <- Model1Forecast$residuals
e2 <- Model2Forecast$residuals
e1sq <- e1^2
e2sq <- e2^2
mean(e1)
mean(e1sq)
mean(e2)
mean(e2sq)
t.test(e1)
t.test(e2)
Box.test(e1, 12, "Lj")
Box.test(e2, 12, "Lj")
eft <- lm(e1~Model1Forecast$fitted)
eft2 <- lm(e2~Model2Forecast$fitted)
summary(eft)
summary(eft2)
lht(eft, c("(Intercept)", "Model1Forecast$fitted"))
linear <- e1 - e2
t.test(linear)
quad <- e1sq - e2sq
t.test(quad)
eff <- lm(logBHPI[344:381]~Model2Forecast$fitted)
summary(eff)
lht(eff, c("(Intercept)", "Model2Forecast$fitted"))
library(urca)
library(vars)
t1 <- ur.df(logBHPI, "trend", 12, "AIC")
summary(t1)
t1 <- ur.df(diff(logBHPI), "drift", 12, "AIC")
summary(t1)
t1 <- ur.df(diff(diff(logBHPI)), "drift", 12, "AIC")
summary(t1)
summary(Model1Forecast)
summary(Model2Forecast)
summary(Model3)
summary(Model4)
summary(Model5)
Model4 <- Arima(logBHPI, c(1,2,3))
Forecast4 <- forecast(Model4, h = 36, level = 0.95)
plot(Forecast4)
US <- ts(BostonHousePriceIndex$US, c(1987, 1), frequency = 12)
difflogUS <- diff(log(US))
data_frame <- data.frame(difflogBHPI, difflogUS)
VARselect(data_frame, 12)
Model4 <- VAR(data_frame, 12)
summary(Model4)
IR1 <- irf(Model4)
plot(IR1)
causality(Model4, difflogUS)
plot(US)
logUS <- log(US)
t2 <- ur.df(logUS, "trend", 12, "AIC")
summary(t2)
t2 <- ur.df(difflogUS, "drift", 12, "AIC")
summary(t2)
ts.plot(logBHPI, logUS, col= c("red", "blue"))
data_frame <- data.frame(logBHPI, logUS)
VARselect(data_frame, 12)
jt <- ca.jo(data_frame, type = "trace", ecdet = "none", K = 12)
summary(jt)
ve <- cajorls(jt, 1)
summary(ve$rlm)